# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-08 09:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buy_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buser', to=settings.AUTH_USER_MODEL, verbose_name='买家'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sale_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suser', to=settings.AUTH_USER_MODEL, verbose_name='卖家'),
        ),
    ]
