# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-08 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btitle', models.CharField(max_length=30, verbose_name='汽车品牌')),
                ('type', models.CharField(max_length=50)),
                ('logo', models.ImageField(null=True, upload_to='static/images', verbose_name='logo')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'db_table': 'Brand',
                'verbose_name_plural': '品牌表',
                'verbose_name': '品牌表',
            },
        ),
    ]
