# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-08 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serbran', models.CharField(max_length=30)),
                ('mileage', models.CharField(max_length=20)),
                ('maintenance', models.BooleanField()),
                ('year', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('picture', models.ImageField(upload_to='static/images')),
                ('num', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('user', models.CharField(max_length=30)),
                ('isPurchase', models.CharField(max_length=30)),
                ('formalitiles', models.CharField(max_length=30)),
                ('debt', models.CharField(max_length=30)),
                ('regist', models.DateTimeField()),
                ('engineNo', models.CharField(max_length=30)),
                ('examine', models.CharField(max_length=30)),
                ('ctitle', models.CharField(max_length=30)),
                ('newprice', models.IntegerField()),
                ('idDel', models.BooleanField(default=False)),
            ],
        ),
    ]
