# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-08 08:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_carinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carinfo',
            options={'verbose_name': '车辆信息', 'verbose_name_plural': '车辆信息'},
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='color',
            field=models.CharField(max_length=30, verbose_name='颜色'),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='ctitle',
            field=models.CharField(max_length=30, verbose_name='车名'),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='debt',
            field=models.BooleanField(default=False, verbose_name='是否有债务'),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='engineNo',
            field=models.CharField(max_length=30, verbose_name='发动机号'),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='examine',
            field=models.IntegerField(choices=[(0, '审核中'), (1, '审核通过'), (2, '审核不通过')], default=0, verbose_name='审核进度'),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='formalitiles',
            field=models.BooleanField(default=False, verbose_name='手续是否齐全'),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='isPurchase',
            field=models.BooleanField(default=True, verbose_name='是否购买'),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='maintenance',
            field=models.BooleanField(default=False, verbose_name='维修记录'),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='mileage',
            field=models.IntegerField(default=0, verbose_name='公里数'),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='newprice',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='新车价格'),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='num',
            field=models.DecimalField(decimal_places=1, max_digits=2, verbose_name='排量'),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='picture',
            field=models.ImageField(upload_to='static/images', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=8, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='regist',
            field=models.DateField(verbose_name='上牌日期'),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='serbran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.Brand'),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='卖家'),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='year',
            field=models.CharField(max_length=30, verbose_name='年份'),
        ),
        migrations.AlterModelTable(
            name='carinfo',
            table='CarInfo',
        ),
    ]
