# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-11 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_auto_20190308_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinfo',
            name='newprice',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='新车价格'),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=6, verbose_name='价格'),
        ),
    ]
