# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-11 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_auto_20190311_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinfo',
            name='newprice',
            field=models.DecimalField(decimal_places=0, max_digits=4, verbose_name='新车价格'),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=4, verbose_name='价格'),
        ),
    ]
