# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-08 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_auto_20190308_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='sex',
            field=models.IntegerField(choices=[(0, '女'), (1, '男')], default=1, max_length=10, verbose_name='性别'),
        ),
    ]
