# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-08 09:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_auto_20190308_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='bankcard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardID', models.CharField(max_length=30, verbose_name='卡号')),
                ('username', models.CharField(max_length=20, verbose_name='开户名')),
                ('type', models.IntegerField(choices=[(0, '储蓄卡'), (1, '信用卡'), (0, '')], verbose_name='类型')),
                ('bank', models.IntegerField(choices=[(0, '中国建设银行'), (1, '中国农业银行'), (2, '中国邮政储蓄'), (2, '中国')], verbose_name='开户行')),
                ('cardStatus', models.IntegerField(choices=[(0, ''), (0, ''), (0, ''), (0, '')], verbose_name='状态')),
            ],
            options={
                'verbose_name_plural': 'bankcard',
                'verbose_name': 'bankcard',
                'db_table': '银行卡',
            },
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='sex',
            field=models.IntegerField(choices=[(1, '男'), (0, '女')], default=1, max_length=10, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='bankcard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bankcard', to=settings.AUTH_USER_MODEL),
        ),
    ]
