# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-11 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_auto_20190310_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='sex',
            field=models.IntegerField(choices=[(0, '女'), (1, '男')], default=1, verbose_name='性别'),
        ),
    ]
